I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpycodes/script_1_1.rpy", line 798, in script
    voice "voice/l_voice/episode1/蘭071补.mp3"(配音配掉了)
  File "renpy/common/00voice.rpy", line 533, in execute_voice
    fn = _audio_eval(fn)
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "game/rpycodes/script_1_1.rpy", line 798, in <module>
    voice "voice/l_voice/episode1/蘭071补.mp3"(配音配掉了)
NameError: name '配音配掉了' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpycodes/script_1_1.rpy", line 798, in script
    voice "voice/l_voice/episode1/蘭071补.mp3"(配音配掉了)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 2232, in execute
    self.call("execute")
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 2220, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\statements.py", line 281, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/00voice.rpy", line 533, in execute_voice
    fn = _audio_eval(fn)
  File "renpy/common/000statements.rpy", line 32, in _audio_eval
    return eval(expr, locals=store.audio.__dict__)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/rpycodes/script_1_1.rpy", line 798, in <module>
    voice "voice/l_voice/episode1/蘭071补.mp3"(配音配掉了)
NameError: name '配音配掉了' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
我们之间的爱恋化作少女来谋杀我 1.0
Tue Nov 29 15:57:06 2022
