I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "game/rpycodes/Interpretation.rpy", line 10, in set_default
    default exp_1 = False
Exception: store.exp_1 is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 192, in script
    python:
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\python.py", line 1061, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 193, in <module>
    renpy.execute_default_statement(True)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\exports.py", line 3797, in execute_default_statement
    i.set_default(start)
  File "game/rpycodes/Interpretation.rpy", line 10, in set_default
    default exp_1 = False
Exception: store.exp_1 is being given a default a second time.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
我们之间的爱恋化作少女来谋杀我 1.0
Mon Jan  9 00:44:23 2023
